"""initial schema (collapses migrations 001-030)

Revision ID: f84560335ce3
Revises: 
Create Date: 2026-04-08 11:50:14.770704
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84560335ce3'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'cli'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor', 'audit_log', ['actor', 'timestamp'], unique=False)
    op.create_index('idx_audit_org', 'audit_log', ['org_id', 'timestamp'], unique=False)
    op.create_table('discord_pulse_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('project_slug', sa.Text(), nullable=False),
    sa.Column('run_date', sa.Text(), nullable=False),
    sa.Column('wow_retention_rate', sa.Float(), nullable=True),
    sa.Column('echo_rate', sa.Float(), nullable=True),
    sa.Column('avg_silence_gap_hours', sa.Float(), nullable=True),
    sa.Column('weekly_active_posters', sa.Integer(), nullable=True),
    sa.Column('retention_delta', sa.Float(), nullable=True),
    sa.Column('echo_rate_delta', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'project_slug', 'run_date')
    )
    op.create_index('idx_discord_pulse_runs_org_date', 'discord_pulse_runs', ['org_id', 'run_date'], unique=False)
    op.create_table('orgs',
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('discord_server_id', sa.Text(), nullable=True),
    sa.Column('twitter_handle', sa.Text(), nullable=True),
    sa.Column('config_json', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('platform_meta',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('prospect_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('run_date', sa.Text(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('dimensions_json', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('rationale_json', sa.Text(), nullable=True),
    sa.Column('enrichment_json', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('graduated_at', sa.Text(), nullable=True),
    sa.Column('rejected_at', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('score_band_low', sa.Float(), nullable=True),
    sa.Column('score_band_high', sa.Float(), nullable=True),
    sa.Column('timing_urgency', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'run_date')
    )
    op.create_index('idx_prospect_scores_date', 'prospect_scores', ['run_date'], unique=False)
    op.create_index('idx_prospect_scores_org', 'prospect_scores', ['org_id'], unique=False)
    op.create_table('schema_version',
    sa.Column('version', sa.Integer(), nullable=False)
    )
    op.create_table('alert_configs',
    sa.Column('config_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('min_severity', sa.Text(), server_default=sa.text("'warning'"), nullable=False),
    sa.Column('telegram_chat_id', sa.Text(), nullable=True),
    sa.Column('discord_webhook_url', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cooldown_hours', sa.Integer(), server_default='4', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_index('idx_alert_configs', 'alert_configs', ['org_id'], unique=False)
    op.create_table('diagnostic_deltas',
    sa.Column('delta_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('run_id_before', sa.Integer(), nullable=False),
    sa.Column('run_id_after', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.Text(), nullable=False),
    sa.Column('value_before', sa.Float(), nullable=True),
    sa.Column('value_after', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('pct_change', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('delta_id')
    )
    op.create_index('idx_deltas_after', 'diagnostic_deltas', ['run_id_after'], unique=False)
    op.create_index('idx_deltas_org', 'diagnostic_deltas', ['org_id', 'metric_name'], unique=False)
    op.create_table('diagnostic_runs',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('run_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('started_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cult_run_id', sa.Text(), nullable=True),
    sa.Column('project_slug', sa.Text(), nullable=True),
    sa.Column('run_date', sa.Text(), nullable=True),
    sa.Column('research_mode', sa.Text(), nullable=True),
    sa.Column('checkpoint_path', sa.Text(), nullable=True),
    sa.Column('overall_grade', sa.Text(), nullable=True),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('sable_verdict', sa.Text(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('run_summary_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_diagnostic_cult_run_id', 'diagnostic_runs', ['cult_run_id'], unique=True)
    op.create_index('idx_diagnostic_org', 'diagnostic_runs', ['org_id'], unique=False)
    op.create_index('idx_diagnostic_slug', 'diagnostic_runs', ['project_slug'], unique=False)
    op.create_table('entities',
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'candidate'"), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'auto'"), nullable=False),
    sa.Column('config_json', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index('idx_entities_org', 'entities', ['org_id'], unique=False)
    op.create_table('entity_centrality_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('degree_centrality', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('betweenness_centrality', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('eigenvector_centrality', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('scored_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('run_date', sa.Text(), nullable=False),
    sa.Column('in_centrality', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('out_centrality', sa.Float(), server_default='0.0', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'entity_id')
    )
    op.create_index('idx_centrality_org', 'entity_centrality_scores', ['org_id'], unique=False)
    op.create_table('entity_decay_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('decay_score', sa.Float(), nullable=False),
    sa.Column('risk_tier', sa.Text(), nullable=False),
    sa.Column('scored_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('run_date', sa.Text(), nullable=True),
    sa.Column('factors_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'entity_id')
    )
    op.create_index('idx_decay_scores_org', 'entity_decay_scores', ['org_id'], unique=False)
    op.create_index('idx_decay_scores_tier', 'entity_decay_scores', ['org_id', 'risk_tier'], unique=False)
    op.create_table('entity_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('source_handle', sa.Text(), nullable=False),
    sa.Column('target_handle', sa.Text(), nullable=False),
    sa.Column('interaction_type', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('first_seen', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.Text(), nullable=True),
    sa.Column('run_date', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entity_interactions_org', 'entity_interactions', ['org_id'], unique=False)
    op.create_index('idx_entity_interactions_source', 'entity_interactions', ['org_id', 'source_handle'], unique=False)
    op.create_index('idx_entity_interactions_type', 'entity_interactions', ['org_id', 'interaction_type'], unique=False)
    op.create_table('entity_watchlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('added_by', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'entity_id')
    )
    op.create_index('idx_watchlist_org', 'entity_watchlist', ['org_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('config_json', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('idx_jobs_org', 'jobs', ['org_id'], unique=False)
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('playbook_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('targets_artifact_id', sa.Text(), nullable=True),
    sa.Column('outcomes_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_playbook_outcomes_org', 'playbook_outcomes', ['org_id'], unique=False)
    op.create_table('playbook_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('artifact_id', sa.Text(), nullable=True),
    sa.Column('targets_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_playbook_targets_org', 'playbook_targets', ['org_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('sync_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('sync_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('started_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('records_synced', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cult_run_id', sa.Text(), nullable=True),
    sa.Column('entities_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('entities_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('handles_added', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tags_added', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tags_replaced', sa.Integer(), server_default='0', nullable=False),
    sa.Column('merge_candidates_created', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('sync_id')
    )
    op.create_index('idx_sync_cult_run_id', 'sync_runs', ['cult_run_id'], unique=False)
    op.create_index('idx_sync_org', 'sync_runs', ['org_id'], unique=False)
    op.create_table('watchlist_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('decay_score', sa.Float(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=True),
    sa.Column('snapshot_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_watchlist_snap', 'watchlist_snapshots', ['org_id', 'entity_id', 'snapshot_at'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('event_types', sa.Text(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Integer(), server_default='1', nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_failure_at', sa.Text(), nullable=True),
    sa.Column('last_failure_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'url')
    )
    op.create_table('workflow_runs',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('workflow_name', sa.Text(), nullable=False),
    sa.Column('workflow_version', sa.Text(), server_default=sa.text("'1.0'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('step_fingerprint', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_workflow_runs_active_lock', 'workflow_runs', ['org_id', 'workflow_name'], unique=True, sqlite_where=sa.text("status IN ('pending', 'running')"), postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_index('idx_workflow_runs_name', 'workflow_runs', ['workflow_name', 'status'], unique=False)
    op.create_index('idx_workflow_runs_org', 'workflow_runs', ['org_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.Column('artifact_type', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('stale', sa.Integer(), server_default='0', nullable=False),
    sa.Column('degraded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_index('idx_artifacts_org', 'artifacts', ['org_id'], unique=False)
    op.create_index('idx_artifacts_type', 'artifacts', ['artifact_type'], unique=False)
    op.create_table('content_items',
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('platform', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('posted_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('idx_content_entity', 'content_items', ['entity_id'], unique=False)
    op.create_index('idx_content_org', 'content_items', ['org_id'], unique=False)
    op.create_table('cost_events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.Column('call_type', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('call_status', sa.Text(), server_default=sa.text("'success'"), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_cost_created', 'cost_events', ['created_at'], unique=False)
    op.create_index('idx_cost_events_org_date', 'cost_events', ['org_id', 'created_at'], unique=False)
    op.create_index('idx_cost_org', 'cost_events', ['org_id'], unique=False)
    op.create_table('entity_handles',
    sa.Column('handle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('handle', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Integer(), server_default='0', nullable=False),
    sa.Column('added_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('handle_id'),
    sa.UniqueConstraint('platform', 'handle')
    )
    op.create_index('idx_handles_entity', 'entity_handles', ['entity_id'], unique=False)
    op.create_index('idx_handles_platform_handle', 'entity_handles', ['platform', 'handle'], unique=False)
    op.create_table('entity_notes',
    sa.Column('note_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index('idx_notes_entity', 'entity_notes', ['entity_id'], unique=False)
    op.create_table('entity_tag_history',
    sa.Column('history_id', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('change_type', sa.Text(), nullable=False),
    sa.Column('tag', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Text(), nullable=True),
    sa.Column('effective_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index('idx_tag_history_entity', 'entity_tag_history', ['entity_id', 'effective_at'], unique=False)
    op.create_index('idx_tag_history_org', 'entity_tag_history', ['org_id', 'tag', 'effective_at'], unique=False)
    op.create_table('entity_tags',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('tag', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('is_current', sa.Integer(), server_default='1', nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=True),
    sa.Column('added_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deactivated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index('idx_entity_tags_current', 'entity_tags', ['entity_id', 'is_current', 'tag'], unique=False)
    op.create_index('idx_entity_tags_tag_current', 'entity_tags', ['tag', 'is_current'], unique=False)
    op.create_index('idx_tags_entity', 'entity_tags', ['entity_id'], unique=False)
    op.create_index('idx_tags_tag', 'entity_tags', ['tag'], unique=False)
    op.create_table('job_steps',
    sa.Column('step_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('step_name', sa.Text(), nullable=False),
    sa.Column('step_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('retries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('input_json', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_index('idx_steps_job', 'job_steps', ['job_id'], unique=False)
    op.create_table('merge_candidates',
    sa.Column('candidate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_a_id', sa.Text(), nullable=False),
    sa.Column('entity_b_id', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_a_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['entity_b_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('candidate_id'),
    sa.UniqueConstraint('entity_a_id', 'entity_b_id')
    )
    op.create_index('idx_merge_candidates_status', 'merge_candidates', ['status'], unique=False)
    op.create_table('workflow_events',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('step_id', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_workflow_events_run', 'workflow_events', ['run_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('step_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('step_name', sa.Text(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('retries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('input_json', sa.Text(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], ),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_index('idx_workflow_steps_run', 'workflow_steps', ['run_id'], unique=False)
    op.create_table('actions',
    sa.Column('action_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('content_item_id', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('action_type', sa.Text(), server_default=sa.text("'general'"), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('operator', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('claimed_at', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('skipped_at', sa.Text(), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.item_id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index('idx_actions_entity', 'actions', ['entity_id'], unique=False, sqlite_where=sa.text('entity_id IS NOT NULL'), postgresql_where=sa.text('entity_id IS NOT NULL'))
    op.create_index('idx_actions_org', 'actions', ['org_id', 'status'], unique=False)
    op.create_index('idx_actions_pending', 'actions', ['org_id', 'created_at'], unique=False, sqlite_where=sa.text("status = 'pending'"), postgresql_where=sa.text("status = 'pending'"))
    op.create_table('merge_events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_entity_id', sa.Text(), nullable=False),
    sa.Column('target_entity_id', sa.Text(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('merged_by', sa.Text(), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['merge_candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=True),
    sa.Column('alert_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('action_id', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Text(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'new'"), nullable=False),
    sa.Column('dedup_key', sa.Text(), nullable=True),
    sa.Column('acknowledged_at', sa.Text(), nullable=True),
    sa.Column('acknowledged_by', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_delivered_at', sa.Text(), nullable=True),
    sa.Column('last_delivery_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.action_id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index('idx_alerts_dedup', 'alerts', ['dedup_key'], unique=False, sqlite_where=sa.text("dedup_key IS NOT NULL AND status = 'new'"), postgresql_where=sa.text("dedup_key IS NOT NULL AND status = 'new'"))
    op.create_index('idx_alerts_org', 'alerts', ['org_id', 'status', 'severity'], unique=False)
    op.create_table('outcomes',
    sa.Column('outcome_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('action_id', sa.Text(), nullable=True),
    sa.Column('outcome_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_name', sa.Text(), nullable=True),
    sa.Column('metric_before', sa.Float(), nullable=True),
    sa.Column('metric_after', sa.Float(), nullable=True),
    sa.Column('metric_delta', sa.Float(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.action_id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('outcome_id')
    )
    op.create_index('idx_outcomes_action', 'outcomes', ['action_id'], unique=False, sqlite_where=sa.text('action_id IS NOT NULL'), postgresql_where=sa.text('action_id IS NOT NULL'))
    op.create_index('idx_outcomes_entity', 'outcomes', ['entity_id'], unique=False, sqlite_where=sa.text('entity_id IS NOT NULL'), postgresql_where=sa.text('entity_id IS NOT NULL'))
    op.create_index('idx_outcomes_org', 'outcomes', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_outcomes_org', table_name='outcomes')
    op.drop_index('idx_outcomes_entity', table_name='outcomes', sqlite_where=sa.text('entity_id IS NOT NULL'), postgresql_where=sa.text('entity_id IS NOT NULL'))
    op.drop_index('idx_outcomes_action', table_name='outcomes', sqlite_where=sa.text('action_id IS NOT NULL'), postgresql_where=sa.text('action_id IS NOT NULL'))
    op.drop_table('outcomes')
    op.drop_index('idx_alerts_org', table_name='alerts')
    op.drop_index('idx_alerts_dedup', table_name='alerts', sqlite_where=sa.text("dedup_key IS NOT NULL AND status = 'new'"), postgresql_where=sa.text("dedup_key IS NOT NULL AND status = 'new'"))
    op.drop_table('alerts')
    op.drop_table('merge_events')
    op.drop_index('idx_actions_pending', table_name='actions', sqlite_where=sa.text("status = 'pending'"), postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('idx_actions_org', table_name='actions')
    op.drop_index('idx_actions_entity', table_name='actions', sqlite_where=sa.text('entity_id IS NOT NULL'), postgresql_where=sa.text('entity_id IS NOT NULL'))
    op.drop_table('actions')
    op.drop_index('idx_workflow_steps_run', table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index('idx_workflow_events_run', table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index('idx_merge_candidates_status', table_name='merge_candidates')
    op.drop_table('merge_candidates')
    op.drop_index('idx_steps_job', table_name='job_steps')
    op.drop_table('job_steps')
    op.drop_index('idx_tags_tag', table_name='entity_tags')
    op.drop_index('idx_tags_entity', table_name='entity_tags')
    op.drop_index('idx_entity_tags_tag_current', table_name='entity_tags')
    op.drop_index('idx_entity_tags_current', table_name='entity_tags')
    op.drop_table('entity_tags')
    op.drop_index('idx_tag_history_org', table_name='entity_tag_history')
    op.drop_index('idx_tag_history_entity', table_name='entity_tag_history')
    op.drop_table('entity_tag_history')
    op.drop_index('idx_notes_entity', table_name='entity_notes')
    op.drop_table('entity_notes')
    op.drop_index('idx_handles_platform_handle', table_name='entity_handles')
    op.drop_index('idx_handles_entity', table_name='entity_handles')
    op.drop_table('entity_handles')
    op.drop_index('idx_cost_org', table_name='cost_events')
    op.drop_index('idx_cost_events_org_date', table_name='cost_events')
    op.drop_index('idx_cost_created', table_name='cost_events')
    op.drop_table('cost_events')
    op.drop_index('idx_content_org', table_name='content_items')
    op.drop_index('idx_content_entity', table_name='content_items')
    op.drop_table('content_items')
    op.drop_index('idx_artifacts_type', table_name='artifacts')
    op.drop_index('idx_artifacts_org', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('idx_workflow_runs_org', table_name='workflow_runs')
    op.drop_index('idx_workflow_runs_name', table_name='workflow_runs')
    op.drop_index('idx_workflow_runs_active_lock', table_name='workflow_runs', sqlite_where=sa.text("status IN ('pending', 'running')"), postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_table('workflow_runs')
    op.drop_table('webhook_subscriptions')
    op.drop_index('idx_watchlist_snap', table_name='watchlist_snapshots')
    op.drop_table('watchlist_snapshots')
    op.drop_index('idx_sync_org', table_name='sync_runs')
    op.drop_index('idx_sync_cult_run_id', table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index('idx_playbook_targets_org', table_name='playbook_targets')
    op.drop_table('playbook_targets')
    op.drop_index('idx_playbook_outcomes_org', table_name='playbook_outcomes')
    op.drop_table('playbook_outcomes')
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_index('idx_jobs_org', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_watchlist_org', table_name='entity_watchlist')
    op.drop_table('entity_watchlist')
    op.drop_index('idx_entity_interactions_type', table_name='entity_interactions')
    op.drop_index('idx_entity_interactions_source', table_name='entity_interactions')
    op.drop_index('idx_entity_interactions_org', table_name='entity_interactions')
    op.drop_table('entity_interactions')
    op.drop_index('idx_decay_scores_tier', table_name='entity_decay_scores')
    op.drop_index('idx_decay_scores_org', table_name='entity_decay_scores')
    op.drop_table('entity_decay_scores')
    op.drop_index('idx_centrality_org', table_name='entity_centrality_scores')
    op.drop_table('entity_centrality_scores')
    op.drop_index('idx_entities_org', table_name='entities')
    op.drop_table('entities')
    op.drop_index('idx_diagnostic_slug', table_name='diagnostic_runs')
    op.drop_index('idx_diagnostic_org', table_name='diagnostic_runs')
    op.drop_index('idx_diagnostic_cult_run_id', table_name='diagnostic_runs')
    op.drop_table('diagnostic_runs')
    op.drop_index('idx_deltas_org', table_name='diagnostic_deltas')
    op.drop_index('idx_deltas_after', table_name='diagnostic_deltas')
    op.drop_table('diagnostic_deltas')
    op.drop_index('idx_alert_configs', table_name='alert_configs')
    op.drop_table('alert_configs')
    op.drop_table('schema_version')
    op.drop_index('idx_prospect_scores_org', table_name='prospect_scores')
    op.drop_index('idx_prospect_scores_date', table_name='prospect_scores')
    op.drop_table('prospect_scores')
    op.drop_table('platform_meta')
    op.drop_table('orgs')
    op.drop_index('idx_discord_pulse_runs_org_date', table_name='discord_pulse_runs')
    op.drop_table('discord_pulse_runs')
    op.drop_index('idx_audit_org', table_name='audit_log')
    op.drop_index('idx_audit_actor', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
